version: "2"
services:
  back:
    build: ./rentsee_back
    ports:
    - "19888:19888"
    depends_on:
    - mongo
  mongo:
    image: mongo
    command: mongod --port 27018
    ports:
    - "27018:27018"
  front:
    build: ./rentsee
    ports:
    - "5000:5000"
